### ISSUE TITLE
<pc> | <lb> outside of word

### ISSUE THREAD

**Issue by GusRiva** [iwein-digital/oxygen-frameworks#1]
In case of insert <pc> or <lb> with caret inside a word, add after current word. This is the same behaviour as new-word.

**Comment by GusRiva** [comment]
El funcionamiento de <lb> ahora es como se supone? @v-millet

**Comment by v-millet** [comment]
Sí, para <lb> sí, pero para <pc> no: todavía se inserta dentro de la <w>. Es cierto que puede haber casos en que eso se necesite, pero lo más frecuente (al menos para mí) es que el <pc> sea un signo anterior o posterior a una palabra o un signo de separación de palabras y en este caso aplica la construcción de 'broken word'.
