### ISSUE TITLE
Dependent line

### ISSUE THREAD

**Issue by v-millet** [iwein-digital/oxygen-frameworks#18]
Please add option of including attribute @ana in `<lb>` with values declared in chapter 5.10 of the Heidelberg KurzDoku

**Comment by GusRiva** [comment]
I don't know if this is a good idea. 
Most of the times you add a `<lb>` you want to ignore the ana attribute, so having a combobox appear and request it would be problematic. You can add it using the attributes bar on the right of the screen. Should I add a function to include directly a `<lb>` with ana = "hc:DependentLine"

**Comment by v-millet** [comment]
That was preciseley my idea: a function to include directly an `<lb>` with ana = "hc:DependentLine" and a combobox asking "hc:RunOverLineAbove" or "hc:RunOverLineBelow".

**Comment by GusRiva** [comment]
Resolved in commit: 8f664d3c83954f47c87ae61a25a87b4929cd23c3
