### ISSUE TITLE
Improve <subst> function

### ISSUE THREAD

**Issue by v-millet** [iwein-digital/oxygen-frameworks#20]
Would be excellent that the <subst>-function would prompt not only the type of deletion and addition (=attribute), but also the text of it, like with abbrevations

**Comment by GusRiva** [comment]
I think we had already discussed this: in many cases we might need to have XML-elements (`<w>`, `<hi>`, etc.) inside `<subst>` and not only text; and concluded that asking for text might be problematic

**Comment by v-millet** [comment]
Don't remember discussing it, but absolutely right!

**Comment by v-millet** [comment]
Nevertheless, the combobox prompting the attribute for the <add>-element only reads "place:". Perhaps we could change it to "Place of addition:"
