### ISSUE TITLE
vñ & vnd

### ISSUE THREAD

**Issue by v-millet** [iwein-digital/oxygen-frameworks#6]
Sería un lujo tener sendas opciones en el menú y con shortcut de teclado para que, con sólo seleccionar esa opción (o con sólo la tecla del shortcut), introdujera todo el complejo
<choice><orig>v</orig><reg>u</reg></choice><choice><am>ñ</am><ex>nd</ex></choice>
o bien:
<choice><orig>v</orig><reg>u</reg></choice>nd
Es decir: con una sola combinación de teclas pondríamos toda la palabra.

**Comment by GusRiva** [comment]
En la nueva pestaña "Full Words" agregué esta opción. ¿Te parece que está bien allí y con ese nombre?  @v-millet

**Comment by v-millet** [comment]
Perfecto! Así más adelante se pueden completar con alguna palabra más
